# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Test(object):
    def setupUi(self, Test):
        Test.setObjectName("Test")
        Test.setWindowModality(QtCore.Qt.NonModal)
        Test.resize(340, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Test.sizePolicy().hasHeightForWidth())
        Test.setSizePolicy(sizePolicy)
        Test.setMinimumSize(QtCore.QSize(340, 300))
        Test.setMaximumSize(QtCore.QSize(340, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("linux.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Test.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Test)
        self.label.setGeometry(QtCore.QRect(180, 30, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Test)
        self.label_2.setGeometry(QtCore.QRect(180, 80, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Test)
        self.label_3.setGeometry(QtCore.QRect(180, 130, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Test)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Test)
        self.label_5.setGeometry(QtCore.QRect(180, 230, 111, 16))
        self.label_5.setObjectName("label_5")
        self.analize = QtWidgets.QPushButton(Test)
        self.analize.setGeometry(QtCore.QRect(30, 180, 111, 23))
        self.analize.setObjectName("analize")
        self.name = QtWidgets.QLineEdit(Test)
        self.name.setGeometry(QtCore.QRect(30, 30, 113, 20))
        self.name.setObjectName("name")
        self.text = QtWidgets.QLineEdit(Test)
        self.text.setGeometry(QtCore.QRect(30, 80, 113, 20))
        self.text.setObjectName("text")
        self.lines = QtWidgets.QLineEdit(Test)
        self.lines.setGeometry(QtCore.QRect(30, 130, 113, 20))
        self.lines.setObjectName("lines")
        self.vowels = QtWidgets.QLineEdit(Test)
        self.vowels.setGeometry(QtCore.QRect(30, 250, 113, 20))
        self.vowels.setObjectName("vowels")
        self.consonants = QtWidgets.QLineEdit(Test)
        self.consonants.setGeometry(QtCore.QRect(180, 250, 113, 20))
        self.consonants.setObjectName("consonants")

        self.retranslateUi(Test)
        QtCore.QMetaObject.connectSlotsByName(Test)

    def retranslateUi(self, Test):
        _translate = QtCore.QCoreApplication.translate
        Test.setWindowTitle(_translate("Test", "GUI Test"))
        self.label.setText(_translate("Test", "File name*"))
        self.label_2.setText(_translate("Test", "Text to write*"))
        self.label_3.setText(_translate("Test", "Number of lines for the file*"))
        self.label_4.setText(_translate("Test", "Number of vowels"))
        self.label_5.setText(_translate("Test", "Number of consonants"))
        self.analize.setText(_translate("Test", "Analize"))
